### ISSUE TITLE
Documentation for contributors

### ISSUE THREAD

**Issue by omaxel** [zetareticoli/cssui#21]
We should add documentation to contribute to this project, including but not limited to:
- branching strategy
- naming conventions;
  - branches;
  - PR titles;
- how to run the project on a local machine;
- how to test components;
- which parts of the projects should be updated when submitting changes (e.g. changes to the `.md` files);
- how to handle components' behavior which can only be implemented with JS.

Before working on that, we should have a more exhaustive list.

**Comment by zetareticoli** [comment]
I've added some basi information about contributing (creating an issue, using labels, etc).

We could open a separated issue for development details.
