### ISSUE TITLE
Prevent text selection on Accordion headings / labels

### ISSUE THREAD

**Issue by chrislachance** [zetareticoli/cssui#32]
Visually, the Accordion headings appear as buttons, yet unlike buttons they allow the heading text / labels to be selected. Would have expected that to be prevented.

https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by zetareticoli** [comment]
Hi @chrislachance 

I've been thinking about it for a while and came to conclusion that selecting accordion heading could be an expected behavior by users.

I know it appears as button, but could host some meaningful content

**Comment by omaxel** [comment]
Most of the implementations I have seen on the web ([Bootstrap](https://getbootstrap.com/docs/5.0/components/accordion/), [jQuery UI](https://jqueryui.com/accordion/), [WAI-ARIA](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html)) uses buttons without any text selection.

Also, from [WAI-ARIA authoring practices](https://www.w3.org/TR/wai-aria-practices/#wai-aria-roles-states-and-properties):

> The title of each accordion header is contained in an element with role `button`.

which natively wouldn't allow text-selection

@zetareticoli: I think that, if we have a valid use case like, we can leave it as it is. What do you think?

@chrislachance: As per your link, you can use the `user-select` property in the meanwhile if you want to prevent the text selection 👍
