### ISSUE TITLE
Accordion item label keyboard focus not visualized on FF and Safari

### ISSUE THREAD

**Issue by syndicatefx** [zetareticoli/cssui#37]
Hi @zetareticoli, first of all nice work!

The accordion item label focus outline, using keyboard navigation, is not displaying properly on Firefox and Safari.
I'm using latest versions on MacOS, but i´m sure the issue persists on Windows too. 
The problem seems to be the `overflow: hidden` here:

```
[data-accordion-item] {
  width: 100%;
  overflow: hidden;
}
```

Removing `overflow: hidden` fixes this issue. I'm not sure why you are using overflow here.
Can you confirm this?
Thanks.

**Comment by syndicatefx** [comment]
Hey, nope not happening on my side, but i am using Safari 15.3

<img width="1457" alt="Screenshot 2022-02-18 at 22 09 19" src="https://user-images.githubusercontent.com/1868037/154768104-56cdc227-a254-4452-bb14-587cf9570f04.png">

**Comment by syndicatefx** [comment]
A workaround to avoiding those bizarre behaviors in Safari would be using `outline-style: solid`, and remove `overflow: hidden`for good.
Something like this:

```
  /* Accordion Item's Label Focus State */
  [data-accordion-item] > input:focus + label  {
    outline: 2px solid #101010;
    outline: 2px solid Highlight;
    outline: 2px solid -webkit-focus-ring-color;
  }
```

**Comment by zetareticoli** [comment]
Would try this and let you know. If works, I'll include it in the next hotfix release. 🙌
