### ISSUE TITLE
Download Link not functioning 

### ISSUE THREAD

**Issue by Anurella** [zetareticoli/cssui#40]
@zetareticoli the download it link on the introduction page triggers no download but refreshes the page.

**Comment by omaxel** [comment]
@zetareticoli: I think @Anurella is referring to the download link in the _Introduction_ section of the documentation.

I create a PR to fix it.

**Comment by Anurella** [comment]
> @zetareticoli: I think @Anurella is referring to the download link in the _Introduction_ section of the documentation.
> 
> I create a PR to fix it.

Yes that link

**Comment by Anurella** [comment]
> Hi @Anurella, thank you for reporting this but it's quite strange 🤔
> 
> Can you access to this link https://www.cssui.dev/cssui.zip ?

Yes I can. thank you

**Comment by zetareticoli** [comment]
> > @zetareticoli: I think @Anurella is referring to the download link in the _Introduction_ section of the documentation.
> 
> > 
> 
> > I create a PR to fix it.
> 
> 
> 
> Yes that link

Sorry, my fault
