### ISSUE TITLE
Modal doesn't close when the escape key is pressed

### ISSUE THREAD

**Issue by seezee** [zetareticoli/cssui#43]
Modal doesn't close when the escape key is pressed. Here's why it should: https://accessibility.18f.gov/keyboard/

This should probably apply to the slider and several other components as well.

**Comment by zetareticoli** [comment]
Hi @seezee,

the modal escape pressing `esc` would require additional Javascript. You could build it on your own or use external libraries.

The focus trap is explained here https://www.cssui.dev/docs/components/modal/#focus-trap

**Comment by zetareticoli** [comment]
Close this issue then. Thanks 🙌
