### ISSUE TITLE
Update Twitter logo to X

### ISSUE THREAD

**Issue by Priyanshu-su30** [zetareticoli/cssui#48]
![Screenshot (208)](https://github.com/user-attachments/assets/238354e7-c933-4fe6-9b98-3cffe512cf31)
The logo needs an update to X
Assign me this task and I'll update

**Comment by Priyanshu-su30** [comment]
@zetareticoli please put label of hacktoberfest

**Comment by Neelesh19634** [comment]
The logo needs an update to X
Assign me this task and I'll update

**Comment by Priyanshu-su30** [comment]
@Neelesh19634 I'm already working on it. You can find different issues.
